### PR TITLE
Merge bmsave

### PR DESCRIPTION
**Pull request by MokhaLeee**

### CODE REVIEW

**Comment by ProjectRevoTPP** [comment]
Stilll cant merge this. Conflicts.

**Comment by MokhaLeee** [comment]
Laterly I may create a new branch, comb through all the structures of the bmsave, and then pull a new merge request after finishing this. This PR could be closed later after Kira figures out his questions.

**Comment by laqieer** [comment]
It is recommended to provide description for a reviewer to learn the current state to decide whether to merge it. It is also good to mark the PR as draft if it is not ready for merge.

**Comment by MokhaLeee** [comment]
> provide description for a reviewer to learn the current state

Thanks for your recommendation! The decompilation on bmsave part does involve a lot of modifition for exiting code.  It is my fault not being able to provide a full explanation on these.

To be honest,  I'm used to pull the merge request as soon as possible after any progress. And then work on the newest code next day to avoid any potential conflict. This time I may do a review after all of this part completed, and pull a new merge request.

**Pull request closed without merging**
