### PR TITLE
Dump a lot of proc scripts - trying to get closer to shiftable

### PR DESCRIPTION
**Pull request by NoahNelson**
Going to make this more automated and find/dump a bunch more.

### CODE REVIEW

**Comment by ProjectRevoTPP** [comment]
Is this meant to be a draft PR or ready to go? I can mark it as one.

**Comment by NoahNelson** [comment]
It matches, so could be merged, or you could wait until I dump the rest of the scripts. Doesn’t really matter 🤷‍♀️

**Comment by NoahNelson** [comment]
better mark it draft actually - more coming soon :)

**Comment by NoahNelson** [comment]
Ok, this is ready now. should be most proc scripts that include pointers, I may have missed a few.

**Pull request merged**
