### PR TITLE
decompile songs to MIDI files

### PR DESCRIPTION
**Pull request by laqieer**
**All Midis Match Completed!🎉**

Status: 🆗

### ℹ️Information on build

It is a huge change so run `make clean` before pull from remote to your local machine, or re-clone a clean git repo to build it. Remember to rebuild `tools/mid2agb` too.

### Practical experience for other disasm/decomp projects

It is a nightmare to match MIDI files. Common problems and solutions are collected here. Hope this doc will make life easier for others.

- [How to dump midis](https://github.com/Kermalis/VGMusicStudio/pull/98)
- [How to fix KEYSH](https://github.com/FireEmblemUniverse/fireemblem8u/pull/137#issuecomment-1113989639)
- [How to fix Wxx](https://github.com/FireEmblemUniverse/fireemblem8u/pull/137#issuecomment-1114278166)
- [How to fix TUNE](https://github.com/FireEmblemUniverse/fireemblem8u/pull/137#issuecomment-1115224535)
- [How to fix PATT](https://github.com/FireEmblemUniverse/fireemblem8u/pull/137#issuecomment-1116531290)
- [How to fix v069](https://github.com/pret/pokeemerald/pull/1593)
- [How to remove Wxx after GOTO](https://github.com/FireEmblemUniverse/fireemblem8u/pull/137#issuecomment-1116548880)
- [How to split Wxx](https://github.com/FireEmblemUniverse/fireemblem8u/pull/137#issuecomment-1116561225)
- [How to match non-Midi songs](https://github.com/FireEmblemUniverse/fireemblem8u/pull/137#issuecomment-1115092255)

### CODE REVIEW

**Comment by laqieer** [comment]
```
sha1sum -c checksum.sha1
fireemblem8.gba: FAILED
sha1sum: WARNING: 1 computed checksum did NOT match
make: *** [Makefile:81: compare] Error 1
```

**Comment by laqieer** [comment]
The songs with different size after conversion are splitted to [`non_matching` folder](https://github.com/laqieer/fireemblem8u/tree/midi/sound/songs/midi/non_matching).

Some songs with same size are still different in several bytes.

Most of them have unordered commands. I added @freshollie's [workarounds](https://github.com/freshollie/sa2/blob/main/tools/mid2agb/agb.cpp#L443) to mid2agb to match some more cases where some of the original compiled midi tracks had a different order to the VOL and KEYSH commands, but the order of those commands is still incorrect sometimes.

**Comment by laqieer** [comment]
`song027` doesn't match due to missing patterns. It affects compression of velocity in Nxx commands too.

[Vanilla](https://github.com/FireEmblemUniverse/fireemblem8u/blob/master/sound/songs/song027.s):
```
song027_2_4:
	.byte		N21	, Dn2, v127
	.byte	W24
	.byte		N21	
	.byte	W24
	.byte		N21	
	.byte	W24
	.byte	PEND
	.byte	PATT	
		.word	song027_2_3
	.byte	PATT	
		.word	song027_2_4
	.byte	PATT	
		.word	song027_2_5
song027_2_6:
	.byte		N44	, Dn2, v127
	.byte	W48
	.byte		N44	
	.byte	W48
	.byte	PEND
	.byte	PATT	
		.word	song027_2_6
```
[Midi](https://github.com/laqieer/fireemblem8u/blob/midi/sound/songs/midi/non_matching/song027.mid)
[Converted](https://github.com/FireEmblemUniverse/fireemblem8u/files/8589154/song027.s.txt):
```
	.byte		        Dn2 
	.byte	W24
	.byte		N21   
	.byte	W24
	.byte		N21   
	.byte	W24
@ 011   ----------------------------------------
	.byte	PATT
	 .word	song027_2_003
@ 012   ----------------------------------------
song027_2_012:
	.byte		N44   , Dn2 , v127
	.byte	W48
	.byte		N44   
	.byte	W48
	.byte	PEND
```

**Comment by laqieer** [comment]
`song067` doesn't match due to only a command order difference: its `KEYSH` appears after `VOL` at the beginning of track 7, while other tracks has a first `KEYSH`. Why?
https://github.com/FireEmblemUniverse/fireemblem8u/blob/94d53ef4d521f3f305412d5244d84cf68f411aa4/sound/songs/song067.s#L2276

https://github.com/pret/pokeemerald/commit/f6131763085175cfbe027089e96afa840e774ea1
https://github.com/laqieer/fireemblem8u/commit/1105344759125c2d4502878237e34505a8eaf17e

**Comment by laqieer** [comment]
[List of all songs with names](https://gist.github.com/laqieer/ea9ae4aa126000348c0e23647cdf9007)

"" = an empty slot with a dummy song
s??? = a song converted from `.mid` file by `MID2AGB`
m??? = a song converted from `.mml` file by `MML2AGB`

**Comment by laqieer** [comment]
# How to fix KEYSH order

Take `song067` as example: https://github.com/FireEmblemUniverse/fireemblem8u/pull/137/commits/65ad23785cc17ecc006caa2abfbc3d3095e919ef

## Reason

If the volume of a track is the same as the max volume of the song, then it can be omitted, and `mid2agb` will add it back automatically before `KEYSH`. A dumper such as `VGMusicStudio` doesn't know the max volume of the song, so it doesn't do the omit for a track, and `mid2agb` will add `KEYSH` before the volume at the head of a track.

## Solution

Set the max volume of the song correctly, adjust all volumes in the song, and delete the volume at that track.

### How to decide the max volume of the song?

There are 2 ways:
- Volume can only be omitted at the track whose volume is equal to the max volume of the song, so volume of the track with reversed order of `KEYSH` and `VOL` at the head is the max volume of the song.
For example: https://github.com/FireEmblemUniverse/fireemblem8u/blob/94d53ef4d521f3f305412d5244d84cf68f411aa4/sound/songs/song067.s#L2275
- `mks4agb` reads the max volume of a song from `mks4agb.ini` and passes it to `mid2agb` with `-V` option, so the max volume of all songs are written here: https://github.com/FireEmblemUniverse/fireemblem8u/pull/137#issuecomment-1113609879
For example: 
`s067 = .\agbfe3_new\bgm\bgm_haru\agbfe3_bgm_op_theme,		0,  02, 50,  10,  20	;ＦＥテーマ（主題部）`

### How to fix volumes in midi?

We need to calculate the new volume:
`volume_in_midi = volume_in_s * 127 / max_volume`
It may not be divisible, so re-check the volume:
`volume_in_s = volume_in_midi * max_volume / 127`
Adjust `volume_in_midi` until it the result matches `volume_in_s`
You can edit volume in `.mid` file using a midi editor such as [MidiQuickFix](http://midiquickfix.sourceforge.net/).

That is a tedious work for all volume commands in all midi files with the same problem, so we may hack a dumper such as `VGMusicStudio` to do the fix or write an extra tool to fix it.

**Comment by laqieer** [comment]
`KEYSH` workaround from sa2 was reverted because it causes mismatch of the position of `KEYSH` in some cases such as `song075`. They get matched after the revert.

**Comment by laqieer** [comment]
`song096` mismatch: `W02 W24` vs `W24 W02` at the end of all 2 tracks. Other bytes match. What's the magic here?
https://github.com/FireEmblemUniverse/fireemblem8u/blob/996184172c1de11a08909978255a689a7c00bda1/sound/songs/song096.s#L25
https://github.com/FireEmblemUniverse/fireemblem8u/blob/996184172c1de11a08909978255a689a7c00bda1/sound/songs/song096.s#L26
https://github.com/FireEmblemUniverse/fireemblem8u/blob/996184172c1de11a08909978255a689a7c00bda1/sound/songs/song096.s#L47
https://github.com/FireEmblemUniverse/fireemblem8u/blob/996184172c1de11a08909978255a689a7c00bda1/sound/songs/song096.s#L48

**Comment by freshollie** [comment]
Confirmed your research, correctly extracted the midis from Music Studio so no need for the mid2agb workaround: https://github.com/freshollie/sa2/commit/5b3f98e56efde0454c3a945be00e23ec6d7f12ec 🥳

**Comment by freshollie** [comment]
Incase it helps you when you are matching the time signatures. I used [`py_midicsv`](https://github.com/timwedde/py_midicsv) to quickly edit the time signature rather then using gba music studio. Means it could be automated

```python
import py_midicsv as pm
import sys


data = pm.midi_to_csv(f'sound/songs/midi/{sys.argv[1]}.mid')

for i in range(len(data)):
    line = data[i]

    if 'Time_signature' in line:
        new_data = line.split(', ')
        new_data[3] = sys.argv[2]
        new_data[4] = str(int(sys.argv[3]) // 2)

        data[i] = ", ".join(new_data)

midi_object = pm.csv_to_midi(data)

with open(f'sound/songs/midi/{sys.argv[1]}.mid', "wb") as output_file:
    midi_writer = pm.FileWriter(output_file)
    midi_writer.write(midi_object)
```

`$ python3 scripts/edit_time_signature.py song0405 5 4`

**Comment by laqieer** [comment]
# How to fix Wxx Commands
Take `song096` as example: https://github.com/FireEmblemUniverse/fireemblem8u/pull/137/commits/570fbc956b29c08fdefab4dd04e408db22163fbe

## Problem
https://github.com/FireEmblemUniverse/fireemblem8u/pull/137#issuecomment-1114054026

## Reason
A dumper such as VGMusicStudio doesn't know the [time signature](https://en.wikipedia.org/wiki/Time_signature) of a song, so it is set to `4/4` by default. If a song's time signature is not equal to `4/4`, `mid2agb` will divide timing with a wrong time signature, so you will see mismatching `Wxx` commands.

## Solution
Fix the time signature.

### How to calculate correct time signature?
`TS = 4/4 x PPQ / 96`
For example: song096 track1
```
@**************** Track 1 (Midi-Chn.1) ****************@

song096_1:
	.byte	KEYSH , song096_key+0
@ 000   ----------------------------------------
	.byte	TEMPO , 150*song096_tbs/2
	.byte		VOICE , 48
	.byte		VOL   , 127*song096_mvl/mxv
	.byte		N04   , Bn4 , v127
	.byte	W04
	.byte		        Gs5 
	.byte	W04
	.byte		N06   , Fs5 
	.byte	W06
	.byte		N04   , Bn5 
	.byte	W04
	.byte		        Fs5 
	.byte	W04
	.byte		N10   , Cs6 
	.byte	W24
	.byte	W02
	.byte	FINE
```
It will match if we put a divider between the 2 wait commands with reversed order, like this:
```
@**************** Track 1 (Midi-Chn.1) ****************@

song096_1:
	.byte	KEYSH , song096_key+0
@ 000   ----------------------------------------
	.byte	TEMPO , 150*song096_tbs/2
	.byte		VOICE , 48
	.byte		VOL   , 127*song096_mvl/mxv
	.byte		N04   , Bn4 , v127
	.byte	W04
	.byte		        Gs5 
	.byte	W04
	.byte		N06   , Fs5 
	.byte	W06
	.byte		N04   , Bn5 
	.byte	W04
	.byte		        Fs5 
	.byte	W04
	.byte		N10   , Cs6 
	.byte	W02
@ 001   ----------------------------------------
	.byte	W24
@ 002   ----------------------------------------
	.byte	FINE
```
In this case, one measure = W04 + W04 + W06 + W04 + W04 + W02 = W24, so we change time signature to 4/4 x 24 / 96 = 1/4, and `W24 W02` will become `W02 W24`.

### How to edit time signature in midi?
There are several ways:
- Hex Editor
[Time Signature Format](http://midi.teragonaudio.com/tech/midifile/time.htm)
For example: `FF 58 04 02 02` (4/4) -> `FF 58 04 01 02` (1/4)
- Midi Dumper
For example: [VGMusicStudio](https://github.com/Kermalis/VGMusicStudio/blob/a5f6e96a91d7b5a07c66111668948fc0a31a6424/VG%20Music%20Studio/UI/MainForm.cs#L487)
- Midi Editor / Converter
I didn't try but it may work as long as you can edit the time signature with it.
- Scripting
For example: https://github.com/FireEmblemUniverse/fireemblem8u/pull/137#issuecomment-1114221179
You can automate the process until match.

**Comment by laqieer** [comment]
```
python3 scripts/edit_time_signature.py song183 1 4
python3 scripts/edit_time_signature.py song185 1 4
python3 scripts/edit_time_signature.py song188 1 4
python3 scripts/edit_time_signature.py song189 1 4
python3 scripts/edit_time_signature.py song190 1 4
python3 scripts/edit_time_signature.py song209 1 4
python3 scripts/edit_time_signature.py song214 1 4
python3 scripts/edit_time_signature.py song221 1 4
python3 scripts/edit_time_signature.py song222 1 4
python3 scripts/edit_time_signature.py song226 1 4
python3 scripts/edit_time_signature.py song231 1 4
python3 scripts/edit_time_signature.py song239 1 4
python3 scripts/edit_time_signature.py song241 1 4
python3 scripts/edit_time_signature.py song242 1 4
python3 scripts/edit_time_signature.py song245 1 4
python3 scripts/edit_time_signature.py song246 1 4
python3 scripts/edit_time_signature.py song248 1 4
python3 scripts/edit_time_signature.py song250 1 4
python3 scripts/edit_time_signature.py song256 1 4
python3 scripts/edit_time_signature.py song259 1 4
python3 scripts/edit_time_signature.py song282 1 4
python3 scripts/edit_time_signature.py song283 1 4
python3 scripts/edit_time_signature.py song284 1 4
python3 scripts/edit_time_signature.py song285 1 4
python3 scripts/edit_time_signature.py song287 1 4
python3 scripts/edit_time_signature.py song288 1 4
python3 scripts/edit_time_signature.py song289 1 4
python3 scripts/edit_time_signature.py song293 1 4
python3 scripts/edit_time_signature.py song294 1 4
python3 scripts/edit_time_signature.py song295 1 4
python3 scripts/edit_time_signature.py song306 1 4
python3 scripts/edit_time_signature.py song308 1 4
python3 scripts/edit_time_signature.py song316 1 4
python3 scripts/edit_time_signature.py song433 1 4
python3 scripts/edit_time_signature.py song443 1 4
python3 scripts/edit_time_signature.py song612 1 4
python3 scripts/edit_time_signature.py song613 1 4
python3 scripts/edit_time_signature.py song620 1 4
python3 scripts/edit_time_signature.py song737 1 4
python3 scripts/edit_time_signature.py song738 1 4
python3 scripts/edit_time_signature.py song895 1 4
python3 scripts/edit_time_signature.py song978 1 4
```
Thanks @freshollie 's script!👍

**Comment by laqieer** [comment]
# MML Compatible Mode
`mid2agb` extension to match songs converted from `.mml` instead of `.mid`

## Reason
Some songs are not converted from MIDI format at first. They are from MML format instead. Therefore `mid2agb` cannot match them. The ideal way to match them is to write a MML dumper to extract them to `.mml` files and reimplement `mml2agb` to convert them to match. However, considering that:
- `mml2agb` (and `ismks4agb`) is an internal tool made by Intelligent Systems, it is not widely used in other GBA games like `mid2agb` (and `mks4agb`)
- `.mml` files are not as common as `.mid` files and connot be played directly by music players
- MML songs are much less than MIDI songs (only 99 in 639) and most of them are simple sound effects

It is not worth to do. Instead, I extend `mid2agb` a bit to match most of them. That's it.

## Usage
```
            -M  MML compatible mode
            -K  print KEYSH before VOICE in MML compatible mode (only work with -M)
            -W  print VOL before VOICE in MML compatible mode (only work with -M)
```

## Difference
1. align all tracks by word instead of only track 1
2. disable note velocity optimization
3. adjust order of `KEYSH`, `VOL`, `VOICE` commands at the head of a track with `-K`, `-W` options and midi meta event marker `k`

However, unlike `.mid` files, `.mml` files are text files written by hand, so it cannot match all MML songs, especially the command order described in `3.`. Because it is hand-written at first after all, any order combination is possible, so it is impossible to match all cases.

**Comment by laqieer** [comment]
# How to fix TUNE

## Reason
https://github.com/Kermalis/VGMusicStudio/issues/99

## Solution
There are 2 ways to fix it:
- re-export it using VGMusicStudio with bug fix: https://github.com/Kermalis/VGMusicStudio/pull/98/commits/5a85cda7b5896639f38691b2ea7e52046e8daddc
- edit it directly using [MidiQuickFix](http://midiquickfix.sourceforge.net/) or any other editor: `correct_tune = wrong_tune + 64`

**Comment by laqieer** [comment]
# Current Progress
matching rate: 96% (571 / 593)

## Unmatched songs
22
|ID|Name|Scenario|
|---|---|---|
|002|agbfe3_bgm_op_theme_i|ＦＥテーマ（イントロつき）|
|007|agbfe3_bgm_wmap_04|ワールドマップ　共通|
|009|agbfe3_bgm_map_pl2|AGBFE3 MAP　女主人公初期|
|010|agbfe3_bgm_map_pl3|AGBFE3 MAP　女主人公中期|
|011|agbfe3_bgm_map_pl4|AGBFE3 MAP　男主人公初期|
|014|agbfe3_bgm_map_pl5|ＰＬマップ　魔殿|
|018|agbfe3_bgm_map_pl8|AGBFE3 ＰＬ塔・遺跡(旧策敵)|
|023|agbfe3_bgm_map_cp4|AGBFE3 ＣＰ塔・地下|
|027|agbfe3_bgm_btl_boss1|AGBFE3 バトル章ボス|
|028|agbfe3_bgm_btl_boss2|AGBFE3 バトル中ボス|
|029|agbfe3_bgm_btl_boss4|AGBFE3 バトルリオン|
|031|agbfe3_bgm_btl_weapon|バトル　主人公専用武器|
|032|agbfe3_bgm_btl_dance|AGBFE3 バトル踊り子ＰＬ|
|036|agbfe3_bgm_evt_advance|イベント　章ＯＰ進撃|
|038|agbfe3_bgm_evt_enemy|AGBFE3 イベント 敵出現|
|044|agbfe3_bgm_evt_lyon|AGBFE3 イベント〜リオン|
|045|agbfe3_bgm_evt_lyon2|イベント　リオン（魔王乗っ取られ）|
|046|agbfe3_bgm_evt_enemy2|イベント　敵語る|
|057|agbfe3_bgm_togijyo_btl|闘技場バトル（外伝バージョン）|
|066|agbfe3_bgm_ed_staff|グランドエンディング〜スタッフロール|
|068|agbfe3_bgm_evt_lyon3|イベント　リオン（オルゴール）|
|069|agbfe3_bgm_evt_last|イベント　最終マップ|

**Comment by laqieer** [comment]
# mid2agb's diff
`mid2agb`'s reimplementation for decomp projects handles the following midi file differently compared with official `mid2agb`.
## Input
[agbfe3_bgm_map_pl3.zip](https://github.com/FireEmblemUniverse/fireemblem8u/files/8606011/agbfe3_bgm_map_pl3.zip)
## Option
`-E -G041 -R020 -P010 -V046`
## Output
[agbfe3_bgm_map_pl3(pret mid2agb).s.txt](https://github.com/FireEmblemUniverse/fireemblem8u/files/8606027/agbfe3_bgm_map_pl3.pret.mid2agb.s.txt)
[agbfe3_bgm_map_pl3(official mid2agb).s.txt](https://github.com/FireEmblemUniverse/fireemblem8u/files/8606029/agbfe3_bgm_map_pl3.official.mid2agb.s.txt)

Further research needed.

**Comment by laqieer** [comment]
# How to fix missing patterns

`mid2agb` has a [complex compression algorithm](https://github.com/pret/pokeemerald/blob/c13d2b567c28f2e837be2210c83a250c0de4778f/tools/mid2agb/midi.cpp#L897) to find patterns. It is calculated according to time splits, so you can add extra time signatures before patterns to manipulate it. You can use a Midi dumper like [VGMusicStudio](https://github.com/Kermalis/VGMusicStudio/blob/a5f6e96a91d7b5a07c66111668948fc0a31a6424/VG%20Music%20Studio/UI/MainForm.cs#L487) or a Midi editor like [MidiQuickFix](http://midiquickfix.sourceforge.net/) to add it. Here are some examples: https://github.com/FireEmblemUniverse/fireemblem8u/pull/137/commits/8d06134c225705c3204ce4202dc8c4beb06c57e6, https://github.com/FireEmblemUniverse/fireemblem8u/pull/137/commits/a0bb889ffc75ad6d045093a86a3aeac64e923928, https://github.com/FireEmblemUniverse/fireemblem8u/pull/137/commits/3dc0b67287424a2467837ef473bced90b58fdb49, https://github.com/FireEmblemUniverse/fireemblem8u/pull/137/commits/0f343ee308e58d621233998cc1f993c0b363308e.

**Comment by laqieer** [comment]
# How to fix length
Some redundant waits after `GOTO` at the end of all tracks.

## Reason
Further research needed. It may be related to https://github.com/Kermalis/VGMusicStudio/pull/98/commits/997a4f734d4c4740ec29847d31ac6cc79a07cb56 hack for https://github.com/Kermalis/VGMusicStudio/issues/36 or `EOT`'s time calculation.

## Solution
It is really easy to fix with any midi editor.

### Example
https://github.com/FireEmblemUniverse/fireemblem8u/pull/137/commits/8d06134c225705c3204ce4202dc8c4beb06c57e6

It doesn't have a priority here because it is rare and easy to fix. For memo only.

**Comment by laqieer** [comment]
# How to split wait command

## Problem
image

## Solution
Matched this with a load of dummy note events 🤦‍♂️
image
(Different song)

This project doesn't have this case. Provided by @freshollie. Refer to [SA2 decomp](https://github.com/freshollie/sa2) if interested. For memo purpose.

**Comment by freshollie** [comment]
# How to fix missing patterns, alternative way

## Problem

`mid2agb` will not compress a pattern if its contents doesn't meet a given threshold of complexity. However, after running the compression algorithm, `mid2agb` will have potentially stripped some of the midi instructions, which it doesn't handle, out of the final assembly.

**For example:**
(Left - original, Right - compiled after extracting from ROM)
image
image

The pattern extracted from the ROM is not complex enough (3 instructions) for the compression algorithm in `mid2agb` to consider compressing, but the original did have enough complexity to compress. We have to assume there was more in this pattern (as it's too small to be fixed with time signature changes)

## Solution

Add an dummy instruction to the pattern (all places where we expect it to be used) which `mid2agb` will consider in the compression.

To fix the above example, a `foot` control command was inserted into the midi in both places where the pattern should be compressed:

image

The instruction doesn't appear in the final assembly because `mid2agb` doesn't handle this instruction

**Pull request merged**
