### PR TITLE
Decompile SALLYCURSOR and related proc script data

### PR DESCRIPTION
**Pull request by Eebit**
As usual, please let me know if there's anything I can do better here! This was a cool learning exercise about how the proc system works.

A couple non-matching functions -- `CallCursorShop` and `sub_8034278`.

For `sub_8034278`, there is something not quite right about how I accessed the variable `gUnknown_02010004`. It's not used anywhere else that I can see. That's the only thing off to get it matching (I think).

For `CallCursorShop`, I could not quite figure out how to get the proper return from `GetChapterEventDataPointer` stored onto the stack. The last commit is my best attempt but it's still not quite right. 

Here's the CompilerExplorer for it: https://cexplore.karathan.at/z/CTWaMz

<details><summary>CallCursorShop</summary>

```diff
	THUMB_FUNC_START CallCursorShop
CallCursorShop: @ 0x08033ED4
	push {r4, lr}
	sub sp, #0x1c
	adds r4, r0, #0
	ldr r0, _08033F0C  @ gRAMChapterData
	ldrb r0, [r0, #0xe]
	lsls r0, r0, #0x18
	asrs r0, r0, #0x18
	bl GetChapterEventDataPointer
-	ldr r0, [r0, #8]
-	str r0, [sp]
	mov r1, sp
	ldr r2, _08033F10  @ gUnknown_0202BCB0
	ldrh r0, [r2, #0x14]
	strb r0, [r1, #0x18]
	ldrh r0, [r2, #0x16]
	strb r0, [r1, #0x19]
	mov r0, sp
	bl CheckForEvents
	cmp r0, #0
	beq _08033F2A
	ldr r0, [sp, #0xc]
	cmp r0, #0x16
	beq _08033F14
	cmp r0, #0x17
	beq _08033F20
	b _08033F2A
	.align 2, 0
_08033F0C: .4byte gRAMChapterData
_08033F10: .4byte gUnknown_0202BCB0
_08033F14:
	ldr r1, [sp, #4]
	movs r0, #0
	adds r2, r4, #0
	bl MakeShopArmory
	b _08033F2A
_08033F20:
	ldr r1, [sp, #4]
	movs r0, #0
	adds r2, r4, #0
	bl MakeShopVendor
_08033F2A:
	add sp, #0x1c
	pop {r4}
	pop {r0}
	bx r0

	THUMB_FUNC_END CallCursorShop
```

</details>

### CODE REVIEW

**Comment by NoahNelson** [comment]
I think this matches?
`void CallCursorShop(ProcPtr proc) {
    struct EventCheckBuffer r0;
    const struct ChapterEventInfo *einfo = GetChapterEventDataPointer(gRAMChapterData.chapterIndex);
    struct EventCheckBuffer *buf;
    r0.eventDef = einfo->unk_08;

    r0.xPos = gUnknown_0202BCB0.playerCursor.x;
    r0.yPos = gUnknown_0202BCB0.playerCursor.y;
    buf = CheckForEvents(&r0);
    if (!buf) {
        return;
    }

    switch (r0.commandId) {
        case 0x16:
            MakeShopArmory(0, r0.eventCode, proc);
            break;
        case 0x17:
            MakeShopVendor(0, r0.eventCode, proc);
            break;
    }

    return;
}`
https://cexplore.karathan.at/z/lfpcv3

**Comment by NoahNelson** [comment]
As for gUnknown_02010004, you can just use 0x2010004 in the code and it matches:
`if (unit->state & 0x02010004) {`

I'm newer at git - is there a way for me to add a commit to this PR to match those functions? Would that be helpful?

**Comment by Eebit** [comment]
Oh wow, thanks a bunch! For sure, you can absolutely feel free to commit to this branch :)

I sent you an invite to "collaborate" on my fork (although I'm not sure if that was a required step since I also checked the "allow edits from maintainers" box on this PR). 

To add commits, I believe you should just need to add my fork as a remote in your local Git client. From the Git CLI I think it's like this:

1. Add my fork as a remote: `git remote add <remote_name> https://github.com/Eebit/fireemblem8u.git`
2. Check that <remote_name> is there with: `git remote -v`
3. Fetch the branches from my fork with `git fetch <remote_name>`
4. Switch to the `sallycursor` branch: `git checkout -b sallycursor <remote_name>/sallycursor`
5. Make your changes
6. Commit your changes as normal with `git add` and `git commit`
7. Push your changes here with `git push <remote_name> sallycursor`

If you have any issues pushing due to permissions, let me know and I'll try to resolve them!

**Comment by MokhaLeee** [comment]
maybe you can take this as reference when deconpiling SALLYCURSOR:
https://github.com/MokhaLeee/FE8U-PrepScreen

**Pull request merged**
